# Generated by Django 2.1.15 on 2021-09-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
